### ISSUE TITLE
How to disable HTTPS

### ISSUE THREAD

**Issue by LAazsx** [ReinerNippes/nextcloud_on_docker#112]
Is there a way to disable HTTPS? I have an IIS server upstream that handles all my Letsencrypt stuff and then forwards the requests to the individual servers.

**Comment by ReinerNippes** [comment]
You may try: 

Comment (#) line 

https://github.com/ReinerNippes/nextcloud_on_docker/blob/master/roles/docker_container/tasks/main.yml#L15
https://github.com/ReinerNippes/nextcloud_on_docker/blob/master/roles/docker_container/tasks/main.yml#L16

Put the fqdn/ip address of your proxy here:

https://github.com/ReinerNippes/nextcloud_on_docker/blob/master/roles/nextcloud_config/defaults/main.yml#L8

instead of `--value={{ traefik_facts.container.NetworkSettings.Networks.backend.IPAddress }}"`

Put 
```
    ports:
      - "80:80"
```
here 
https://github.com/ReinerNippes/nextcloud_on_docker/blob/master/roles/docker_container/tasks/nginx.yml#L27

That should disable traefik and open port 80 to your IIS.

**Comment by LAazsx** [comment]
Hello,

Sorry for the late reply, things got crazy at work. Anyway, got it to work!  

I disabled [https://github.com/ReinerNippes/nextcloud_on_docker/blob/master/roles/nextcloud_config/defaults/main.yml#L8](url) as well as we won't route internal traffic through the proxy.
