### ISSUE TITLE
Questions about the installation steps

### ISSUE THREAD

**Issue by Friday13th87** [ReinerNippes/nextcloud_on_docker#95]
Hello there,
just saw your installation script and went through the installation description and have a couple of questions:

1. At the collabora dictionary part its written in the comment that the default dioct is german "de", does that mean if the variable is set to 'en' it will install german + english or do you need to 'de en' to get those two dicts

2. At the Portainer part its written "and provide fqdn. Fqdn is required due to portainer being routed through traefik." but there is no fqdn variable to set. should i just write in a new line
portainer_fqdn = 'portainer.cloud.com' 
or where so i set the requiered fqdn?

3. Is the "fulltextsearch" option something integrated in nextcloud which will be enabled by setting it to true or is this any plugin / extra program / extra container which will be installed alongeside nextcloud to get a better search feature? (i saw several search programs for nextcloud in extra containers, i was just wondering what that fulltextsearch would be)

4. Is the Nextcloud Mail Setting for an actually integrated mailserver or the nextcloud mail app (mail client)?

5. Will collabora be installed in a separate container or as a nextcloud app? 

6. Is there any big difference in speed using the docker setup vs using your 'normal' installation script?
 

Sorry for all those questions but its hard for me doing the installation without those informations. currently i am on a self made docker-compose installation and as i am switching server currently i thought about giving your script a try and make some test before finalizing my setup with my new server.

thanks a ton for your great work

**Comment by Friday13th87** [comment]
I run the script now and the 3rd question is some kind of answered. Its using "tesseract" as is seems, but the installation failed and says that its not compatible with my server version:
`failed: [localhost] (item=files_fulltextsearch_tesseract) => changed=true 
  ansible_loop_var: item
  cmd: docker exec --user www-data nextcloud php occ app:install files_fulltextsearch_tesseract
  delta: '0:00:00.992317'
  end: '2021-03-09 19:47:10.675169'
  item: files_fulltextsearch_tesseract
  msg: non-zero return code
  rc: 1
  start: '2021-03-09 19:47:09.682852'
  stderr: ''
  stderr_lines: <omitted>
  stdout: 'Error: App "Full text search - Files - Tesseract OCR" cannot be installed because it is not compatible with this version of the server.'
  stdout_lines: <omitted>
`

5. --> collabora runs in its own container linked to nextcloud

aaaand i have the same errors / security warnings as in my own setup:
php-imagick not installed, "/.well-known/webfinger" and "/.well-known/nodeinfo" are not propably resolved by nginx

i think i will give the normal installation a try now

**Comment by ReinerNippes** [comment]
> do you need to 'de en' to get those two dicts

for my understanding this is the correct way to have both dicts. 

>  At the Portainer part its written

i corrected the readme and the according line in the inventory. sorry for the confusion. there is no fqdn needed for portainer.

> fulltextsearch 

is - i think - currently broken. i have to look at it again. 
the playbook would start an elasticsearch container and configure the fulltextsearch app in nextcloud. but fulltextsearch is imho work in progress and i can't catch up with them.

> mail setting 

you'll find the mail setting at this page:

https://docs.nextcloud.com/server/21/admin_manual/configuration_server/email_configuration.html

> collabora

yes. it's the container version. 

> speed.

the docker playbook is faster. (depends on the internet connection of your server.) because installing apt and/or rpm packages is really slow. compared with downloading and starting of a containers. 

the speed of nextcloud? well. i think it doesn't matter if you run "on os" or inside a container. but that might depend on your usage. (just some mobile uploads or 10.000 users) 

> warnings
> php-imagick not installed, 

well. it's the "offical" nextcloud gmbh image. so if you care about this warning open a ticket at github.com/nextcloud/docker or just wait for 21.0.1

> "/.well-known/webfinger" and "/.well-known/nodeinfo"

that's because traefik handles the redirect and not nginx. I have to look into this.

"/.well-known/webfinger" and "/.well-known/nodeinfo"
